ports:
  - port: 3000
tasks:
  - init: >
      cd language-server &&
      ./gradlew build &&
      cd ../theia &&
      yarn &&
      cd ..
    command: >
      cd theia/browser-app &&
      yarn start --hostname=0.0.0.0 ../../ws-theia

