image:
     file: .gitpod.dockerfile
ports:
  - port: 3000
tasks:
  - init: |
      ./language-server/gradlew -p language-server build
      yarn --cwd theia
    command: |
      yarn --cwd theia/browser-app start --hostname=0.0.0.0 ../../ws-theia
