/*
 * generated by Xtext 2.19.0
 */
package yu0323.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractRucmScopeProvider extends DelegatingScopeProvider {
}
