/*
 * generated by Xtext 2.19.0
 */
package yu0323.ide.contentassist.antlr;

import com.google.common.collect.ImmutableMap;
import com.google.inject.Inject;
import com.google.inject.Singleton;
import java.util.Map;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ide.editor.contentassist.antlr.AbstractContentAssistParser;
import yu0323.ide.contentassist.antlr.internal.InternalRucmParser;
import yu0323.services.RucmGrammarAccess;

public class RucmParser extends AbstractContentAssistParser {

	@Singleton
	public static final class NameMappings {
		
		private final Map<AbstractElement, String> mappings;
		
		@Inject
		public NameMappings(RucmGrammarAccess grammarAccess) {
			ImmutableMap.Builder<AbstractElement, String> builder = ImmutableMap.builder();
			init(builder, grammarAccess);
			this.mappings = builder.build();
		}
		
		public String getRuleName(AbstractElement element) {
			return mappings.get(element);
		}
		
		private static void init(ImmutableMap.Builder<AbstractElement, String> builder, RucmGrammarAccess grammarAccess) {
			builder.put(grammarAccess.getUCModelAccess().getAlternatives_2(), "rule__UCModel__Alternatives_2");
			builder.put(grammarAccess.getUCModelAccess().getGroup(), "rule__UCModel__Group__0");
			builder.put(grammarAccess.getActorAccess().getGroup(), "rule__Actor__Group__0");
			builder.put(grammarAccess.getUseCaseAccess().getGroup(), "rule__UseCase__Group__0");
			builder.put(grammarAccess.getRelationshipAccess().getGroup(), "rule__Relationship__Group__0");
			builder.put(grammarAccess.getUCModelAccess().getNameAssignment_1(), "rule__UCModel__NameAssignment_1");
			builder.put(grammarAccess.getUCModelAccess().getActorAssignment_2_0(), "rule__UCModel__ActorAssignment_2_0");
			builder.put(grammarAccess.getUCModelAccess().getUsecaseAssignment_2_1(), "rule__UCModel__UsecaseAssignment_2_1");
			builder.put(grammarAccess.getActorAccess().getNameAssignment_1(), "rule__Actor__NameAssignment_1");
			builder.put(grammarAccess.getActorAccess().getRelationshipAssignment_2(), "rule__Actor__RelationshipAssignment_2");
			builder.put(grammarAccess.getUseCaseAccess().getNameAssignment_1(), "rule__UseCase__NameAssignment_1");
			builder.put(grammarAccess.getRelationshipAccess().getActorAssignment_0(), "rule__Relationship__ActorAssignment_0");
			builder.put(grammarAccess.getRelationshipAccess().getUsecaseAssignment_2(), "rule__Relationship__UsecaseAssignment_2");
		}
	}
	
	@Inject
	private NameMappings nameMappings;

	@Inject
	private RucmGrammarAccess grammarAccess;

	@Override
	protected InternalRucmParser createParser() {
		InternalRucmParser result = new InternalRucmParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}

	@Override
	protected String getRuleName(AbstractElement element) {
		return nameMappings.getRuleName(element);
	}

	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}

	public RucmGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(RucmGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
	public NameMappings getNameMappings() {
		return nameMappings;
	}
	
	public void setNameMappings(NameMappings nameMappings) {
		this.nameMappings = nameMappings;
	}
}
