/*
 * generated by Xtext 2.19.0
 */
package yu0323.ide

import yu0323.ide.AbstractRucmIdeModule

/**
 * Use this class to register ide components.
 */
class RucmIdeModule extends AbstractRucmIdeModule {
    def Class<? extends ICodeActionService> bindICodeActionService() {
		StatesCodeActionService
	}
}
