/**
 * generated by Xtext 2.19.0
 */
package yu0323.tests;

import com.google.inject.Inject;
import org.eclipse.emf.common.util.EList;
import org.eclipse.emf.ecore.resource.Resource;
import org.eclipse.xtend2.lib.StringConcatenation;
import org.eclipse.xtext.testing.InjectWith;
import org.eclipse.xtext.testing.extensions.InjectionExtension;
import org.eclipse.xtext.testing.util.ParseHelper;
import org.eclipse.xtext.xbase.lib.Exceptions;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import yu0323.rucm.UCModel;
import yu0323.tests.RucmInjectorProvider;

@ExtendWith(InjectionExtension.class)
@InjectWith(RucmInjectorProvider.class)
@SuppressWarnings("all")
public class RucmParsingTest {
  @Inject
  private ParseHelper<UCModel> parseHelper;
  
  @Test
  public void loadModel() {
    try {
      StringConcatenation _builder = new StringConcatenation();
      _builder.append("ucmodel example");
      _builder.newLine();
      _builder.newLine();
      _builder.append("actor yuyue");
      _builder.newLine();
      _builder.newLine();
      _builder.append("usecase drive");
      _builder.newLine();
      _builder.append("usecase stop");
      _builder.newLine();
      final UCModel result = this.parseHelper.parse(_builder);
      Assertions.assertNotNull(result);
      final EList<Resource.Diagnostic> errors = result.eResource().getErrors();
      boolean _isEmpty = errors.isEmpty();
      StringConcatenation _builder_1 = new StringConcatenation();
      _builder_1.append("Unexpected errors: «errors.join(\", \")»");
      Assertions.assertTrue(_isEmpty, _builder_1.toString());
    } catch (Throwable _e) {
      throw Exceptions.sneakyThrow(_e);
    }
  }
}
