/**
 * generated by Xtext 2.19.0
 */
package yu0323.validation;

import yu0323.validation.AbstractRucmValidator;

/**
 * This class contains custom validation rules.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
@SuppressWarnings("all")
public class RucmValidator extends AbstractRucmValidator {
}
