/**
 * generated by Xtext 2.19.0
 */
package yu0323.rucm;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see yu0323.rucm.RucmFactory
 * @model kind="package"
 * @generated
 */
public interface RucmPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "rucm";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.Rucm.yu0323";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "rucm";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  RucmPackage eINSTANCE = yu0323.rucm.impl.RucmPackageImpl.init();

  /**
   * The meta object id for the '{@link yu0323.rucm.impl.UCModelImpl <em>UC Model</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see yu0323.rucm.impl.UCModelImpl
   * @see yu0323.rucm.impl.RucmPackageImpl#getUCModel()
   * @generated
   */
  int UC_MODEL = 0;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int UC_MODEL__NAME = 0;

  /**
   * The feature id for the '<em><b>Actor</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int UC_MODEL__ACTOR = 1;

  /**
   * The feature id for the '<em><b>Usecase</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int UC_MODEL__USECASE = 2;

  /**
   * The number of structural features of the '<em>UC Model</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int UC_MODEL_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link yu0323.rucm.impl.ActorImpl <em>Actor</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see yu0323.rucm.impl.ActorImpl
   * @see yu0323.rucm.impl.RucmPackageImpl#getActor()
   * @generated
   */
  int ACTOR = 1;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ACTOR__NAME = 0;

  /**
   * The feature id for the '<em><b>Relationship</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ACTOR__RELATIONSHIP = 1;

  /**
   * The number of structural features of the '<em>Actor</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ACTOR_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link yu0323.rucm.impl.UseCaseImpl <em>Use Case</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see yu0323.rucm.impl.UseCaseImpl
   * @see yu0323.rucm.impl.RucmPackageImpl#getUseCase()
   * @generated
   */
  int USE_CASE = 2;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int USE_CASE__NAME = 0;

  /**
   * The number of structural features of the '<em>Use Case</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int USE_CASE_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link yu0323.rucm.impl.RelationshipImpl <em>Relationship</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see yu0323.rucm.impl.RelationshipImpl
   * @see yu0323.rucm.impl.RucmPackageImpl#getRelationship()
   * @generated
   */
  int RELATIONSHIP = 3;

  /**
   * The feature id for the '<em><b>Actor</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RELATIONSHIP__ACTOR = 0;

  /**
   * The feature id for the '<em><b>Usecase</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RELATIONSHIP__USECASE = 1;

  /**
   * The number of structural features of the '<em>Relationship</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RELATIONSHIP_FEATURE_COUNT = 2;


  /**
   * Returns the meta object for class '{@link yu0323.rucm.UCModel <em>UC Model</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>UC Model</em>'.
   * @see yu0323.rucm.UCModel
   * @generated
   */
  EClass getUCModel();

  /**
   * Returns the meta object for the attribute '{@link yu0323.rucm.UCModel#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see yu0323.rucm.UCModel#getName()
   * @see #getUCModel()
   * @generated
   */
  EAttribute getUCModel_Name();

  /**
   * Returns the meta object for the containment reference list '{@link yu0323.rucm.UCModel#getActor <em>Actor</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Actor</em>'.
   * @see yu0323.rucm.UCModel#getActor()
   * @see #getUCModel()
   * @generated
   */
  EReference getUCModel_Actor();

  /**
   * Returns the meta object for the containment reference list '{@link yu0323.rucm.UCModel#getUsecase <em>Usecase</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Usecase</em>'.
   * @see yu0323.rucm.UCModel#getUsecase()
   * @see #getUCModel()
   * @generated
   */
  EReference getUCModel_Usecase();

  /**
   * Returns the meta object for class '{@link yu0323.rucm.Actor <em>Actor</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Actor</em>'.
   * @see yu0323.rucm.Actor
   * @generated
   */
  EClass getActor();

  /**
   * Returns the meta object for the attribute '{@link yu0323.rucm.Actor#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see yu0323.rucm.Actor#getName()
   * @see #getActor()
   * @generated
   */
  EAttribute getActor_Name();

  /**
   * Returns the meta object for the containment reference list '{@link yu0323.rucm.Actor#getRelationship <em>Relationship</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Relationship</em>'.
   * @see yu0323.rucm.Actor#getRelationship()
   * @see #getActor()
   * @generated
   */
  EReference getActor_Relationship();

  /**
   * Returns the meta object for class '{@link yu0323.rucm.UseCase <em>Use Case</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Use Case</em>'.
   * @see yu0323.rucm.UseCase
   * @generated
   */
  EClass getUseCase();

  /**
   * Returns the meta object for the attribute '{@link yu0323.rucm.UseCase#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see yu0323.rucm.UseCase#getName()
   * @see #getUseCase()
   * @generated
   */
  EAttribute getUseCase_Name();

  /**
   * Returns the meta object for class '{@link yu0323.rucm.Relationship <em>Relationship</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Relationship</em>'.
   * @see yu0323.rucm.Relationship
   * @generated
   */
  EClass getRelationship();

  /**
   * Returns the meta object for the reference '{@link yu0323.rucm.Relationship#getActor <em>Actor</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Actor</em>'.
   * @see yu0323.rucm.Relationship#getActor()
   * @see #getRelationship()
   * @generated
   */
  EReference getRelationship_Actor();

  /**
   * Returns the meta object for the reference '{@link yu0323.rucm.Relationship#getUsecase <em>Usecase</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Usecase</em>'.
   * @see yu0323.rucm.Relationship#getUsecase()
   * @see #getRelationship()
   * @generated
   */
  EReference getRelationship_Usecase();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  RucmFactory getRucmFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link yu0323.rucm.impl.UCModelImpl <em>UC Model</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see yu0323.rucm.impl.UCModelImpl
     * @see yu0323.rucm.impl.RucmPackageImpl#getUCModel()
     * @generated
     */
    EClass UC_MODEL = eINSTANCE.getUCModel();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute UC_MODEL__NAME = eINSTANCE.getUCModel_Name();

    /**
     * The meta object literal for the '<em><b>Actor</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference UC_MODEL__ACTOR = eINSTANCE.getUCModel_Actor();

    /**
     * The meta object literal for the '<em><b>Usecase</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference UC_MODEL__USECASE = eINSTANCE.getUCModel_Usecase();

    /**
     * The meta object literal for the '{@link yu0323.rucm.impl.ActorImpl <em>Actor</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see yu0323.rucm.impl.ActorImpl
     * @see yu0323.rucm.impl.RucmPackageImpl#getActor()
     * @generated
     */
    EClass ACTOR = eINSTANCE.getActor();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ACTOR__NAME = eINSTANCE.getActor_Name();

    /**
     * The meta object literal for the '<em><b>Relationship</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ACTOR__RELATIONSHIP = eINSTANCE.getActor_Relationship();

    /**
     * The meta object literal for the '{@link yu0323.rucm.impl.UseCaseImpl <em>Use Case</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see yu0323.rucm.impl.UseCaseImpl
     * @see yu0323.rucm.impl.RucmPackageImpl#getUseCase()
     * @generated
     */
    EClass USE_CASE = eINSTANCE.getUseCase();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute USE_CASE__NAME = eINSTANCE.getUseCase_Name();

    /**
     * The meta object literal for the '{@link yu0323.rucm.impl.RelationshipImpl <em>Relationship</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see yu0323.rucm.impl.RelationshipImpl
     * @see yu0323.rucm.impl.RucmPackageImpl#getRelationship()
     * @generated
     */
    EClass RELATIONSHIP = eINSTANCE.getRelationship();

    /**
     * The meta object literal for the '<em><b>Actor</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference RELATIONSHIP__ACTOR = eINSTANCE.getRelationship_Actor();

    /**
     * The meta object literal for the '<em><b>Usecase</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference RELATIONSHIP__USECASE = eINSTANCE.getRelationship_Usecase();

  }

} //RucmPackage
