/**
 * generated by Xtext 2.19.0
 */
package yu0323.rucm;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>UC Model</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link yu0323.rucm.UCModel#getName <em>Name</em>}</li>
 *   <li>{@link yu0323.rucm.UCModel#getActor <em>Actor</em>}</li>
 *   <li>{@link yu0323.rucm.UCModel#getUsecase <em>Usecase</em>}</li>
 * </ul>
 *
 * @see yu0323.rucm.RucmPackage#getUCModel()
 * @model
 * @generated
 */
public interface UCModel extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Name</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see yu0323.rucm.RucmPackage#getUCModel_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link yu0323.rucm.UCModel#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Actor</b></em>' containment reference list.
   * The list contents are of type {@link yu0323.rucm.Actor}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Actor</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Actor</em>' containment reference list.
   * @see yu0323.rucm.RucmPackage#getUCModel_Actor()
   * @model containment="true"
   * @generated
   */
  EList<Actor> getActor();

  /**
   * Returns the value of the '<em><b>Usecase</b></em>' containment reference list.
   * The list contents are of type {@link yu0323.rucm.UseCase}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Usecase</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Usecase</em>' containment reference list.
   * @see yu0323.rucm.RucmPackage#getUCModel_Usecase()
   * @model containment="true"
   * @generated
   */
  EList<UseCase> getUsecase();

} // UCModel
