/**
 * generated by Xtext 2.19.0
 */
package yu0323;

import yu0323.RucmStandaloneSetupGenerated;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
@SuppressWarnings("all")
public class RucmStandaloneSetup extends RucmStandaloneSetupGenerated {
  public static void doSetup() {
    new RucmStandaloneSetup().createInjectorAndDoEMFRegistration();
  }
}
