/**
 * generated by Xtext 2.19.0
 */
package yu0323;

import yu0323.AbstractRucmRuntimeModule;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
@SuppressWarnings("all")
public class RucmRuntimeModule extends AbstractRucmRuntimeModule {
}
