/**
 * generated by Xtext 2.19.0
 */
package yu0323.ide;

import yu0323.ide.AbstractRucmIdeModule;

/**
 * Use this class to register ide components.
 */
@SuppressWarnings("all")
public class RucmIdeModule extends AbstractRucmIdeModule {
}
