/*
 * generated by Xtext 2.19.0
 */
package yu0323


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class RucmStandaloneSetup extends RucmStandaloneSetupGenerated {

	def static void doSetup() {
		new RucmStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
